# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\POO\PROYECTOS\Proyectoe\Ui\Meseros\Menuscroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1091, 501)
        Form.setMinimumSize(QtCore.QSize(1091, 501))
        Form.setMaximumSize(QtCore.QSize(1091, 501))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(110, 0, 981, 501))
        self.widget.setMinimumSize(QtCore.QSize(0, 501))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 501))
        self.widget.setStyleSheet("QWidget{\n"
"background-color: #333333;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(50, 50, 731, 441))
        self.scrollArea.setStyleSheet("background-color: #f5f5f5;\n"
"border-radius: 50px;\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 710, 661))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.fuertec_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_8.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_8.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_8.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_8.setText("")
        self.fuertec_8.setObjectName("fuertec_8")
        self.gridLayout.addWidget(self.fuertec_8, 8, 4, 1, 1)
        self.bebidasc7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc7.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc7.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc7.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc7.setObjectName("bebidasc7")
        self.gridLayout.addWidget(self.bebidasc7, 21, 2, 1, 1)
        self.postrec_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.postrec_5.setMinimumSize(QtCore.QSize(51, 21))
        self.postrec_5.setMaximumSize(QtCore.QSize(51, 21))
        self.postrec_5.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.postrec_5.setText("")
        self.postrec_5.setObjectName("postrec_5")
        self.gridLayout.addWidget(self.postrec_5, 17, 4, 1, 1)
        self.postre_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.postre_6.setMinimumSize(QtCore.QSize(191, 21))
        self.postre_6.setMaximumSize(QtCore.QSize(191, 21))
        self.postre_6.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.postre_6.setObjectName("postre_6")
        self.gridLayout.addWidget(self.postre_6, 18, 3, 1, 1)
        self.postre_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.postre_5.setMinimumSize(QtCore.QSize(191, 21))
        self.postre_5.setMaximumSize(QtCore.QSize(191, 21))
        self.postre_5.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.postre_5.setObjectName("postre_5")
        self.gridLayout.addWidget(self.postre_5, 17, 3, 1, 1)
        self.fuertec_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_3.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_3.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_3.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_3.setText("")
        self.fuertec_3.setObjectName("fuertec_3")
        self.gridLayout.addWidget(self.fuertec_3, 3, 4, 1, 1)
        self.ensaladac_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ensaladac_5.setMinimumSize(QtCore.QSize(51, 21))
        self.ensaladac_5.setMaximumSize(QtCore.QSize(51, 21))
        self.ensaladac_5.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.ensaladac_5.setText("")
        self.ensaladac_5.setObjectName("ensaladac_5")
        self.gridLayout.addWidget(self.ensaladac_5, 24, 4, 1, 1)
        self.ensaladas_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ensaladas_2.setMinimumSize(QtCore.QSize(191, 21))
        self.ensaladas_2.setMaximumSize(QtCore.QSize(191, 21))
        self.ensaladas_2.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.ensaladas_2.setObjectName("ensaladas_2")
        self.gridLayout.addWidget(self.ensaladas_2, 21, 3, 1, 1)
        self.postre_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.postre_4.setMinimumSize(QtCore.QSize(191, 21))
        self.postre_4.setMaximumSize(QtCore.QSize(191, 21))
        self.postre_4.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.postre_4.setObjectName("postre_4")
        self.gridLayout.addWidget(self.postre_4, 16, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 19, 3, 1, 1)
        self.ensaladas_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ensaladas_4.setMinimumSize(QtCore.QSize(191, 21))
        self.ensaladas_4.setMaximumSize(QtCore.QSize(191, 21))
        self.ensaladas_4.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.ensaladas_4.setObjectName("ensaladas_4")
        self.gridLayout.addWidget(self.ensaladas_4, 23, 3, 1, 1)
        self.ensaladac_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ensaladac_4.setMinimumSize(QtCore.QSize(51, 21))
        self.ensaladac_4.setMaximumSize(QtCore.QSize(51, 21))
        self.ensaladac_4.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.ensaladac_4.setText("")
        self.ensaladac_4.setObjectName("ensaladac_4")
        self.gridLayout.addWidget(self.ensaladac_4, 23, 4, 1, 1)
        self.postre_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.postre_2.setMinimumSize(QtCore.QSize(191, 21))
        self.postre_2.setMaximumSize(QtCore.QSize(191, 21))
        self.postre_2.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.postre_2.setObjectName("postre_2")
        self.gridLayout.addWidget(self.postre_2, 13, 3, 1, 1)
        self.bebidasc8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc8.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc8.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc8.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc8.setObjectName("bebidasc8")
        self.gridLayout.addWidget(self.bebidasc8, 22, 2, 1, 1)
        self.ensaladas_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ensaladas_5.setMinimumSize(QtCore.QSize(191, 21))
        self.ensaladas_5.setMaximumSize(QtCore.QSize(191, 21))
        self.ensaladas_5.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.ensaladas_5.setObjectName("ensaladas_5")
        self.gridLayout.addWidget(self.ensaladas_5, 24, 3, 1, 1)
        self.bebidasc1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc1.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc1.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc1.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc1.setText("")
        self.bebidasc1.setObjectName("bebidasc1")
        self.gridLayout.addWidget(self.bebidasc1, 15, 2, 1, 1)
        self.postrec_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.postrec_4.setMinimumSize(QtCore.QSize(51, 21))
        self.postrec_4.setMaximumSize(QtCore.QSize(51, 21))
        self.postrec_4.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.postrec_4.setText("")
        self.postrec_4.setObjectName("postrec_4")
        self.gridLayout.addWidget(self.postrec_4, 16, 4, 1, 1)
        self.bebidasc9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc9.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc9.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc9.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc9.setObjectName("bebidasc9")
        self.gridLayout.addWidget(self.bebidasc9, 23, 2, 1, 1)
        self.fuertec_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_5.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_5.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_5.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_5.setText("")
        self.fuertec_5.setObjectName("fuertec_5")
        self.gridLayout.addWidget(self.fuertec_5, 5, 4, 1, 1)
        self.bebidas8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas8.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas8.setObjectName("bebidas8")
        self.gridLayout.addWidget(self.bebidas8, 22, 0, 1, 1)
        self.fuerte3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte3.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte3.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte3.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte3.setObjectName("fuerte3")
        self.gridLayout.addWidget(self.fuerte3, 3, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 3, 1, 1)
        self.fuerte5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte5.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte5.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte5.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte5.setObjectName("fuerte5")
        self.gridLayout.addWidget(self.fuerte5, 5, 3, 1, 1)
        self.entradac5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac5.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac5.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac5.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac5.setObjectName("entradac5")
        self.gridLayout.addWidget(self.entradac5, 5, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 10, 3, 1, 1)
        self.bebidas10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas10.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas10.setObjectName("bebidas10")
        self.gridLayout.addWidget(self.bebidas10, 24, 0, 1, 1)
        self.bebidasc5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc5.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc5.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc5.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc5.setObjectName("bebidasc5")
        self.gridLayout.addWidget(self.bebidasc5, 19, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.ensaladac_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ensaladac_3.setMinimumSize(QtCore.QSize(51, 21))
        self.ensaladac_3.setMaximumSize(QtCore.QSize(51, 21))
        self.ensaladac_3.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.ensaladac_3.setText("")
        self.ensaladac_3.setObjectName("ensaladac_3")
        self.gridLayout.addWidget(self.ensaladac_3, 22, 4, 1, 1)
        self.fuerte4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte4.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte4.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte4.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte4.setObjectName("fuerte4")
        self.gridLayout.addWidget(self.fuerte4, 4, 3, 1, 1)
        self.bebidas7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas7.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas7.setObjectName("bebidas7")
        self.gridLayout.addWidget(self.bebidas7, 21, 0, 1, 1)
        self.bebidas2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas2.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas2.setObjectName("bebidas2")
        self.gridLayout.addWidget(self.bebidas2, 16, 0, 1, 1)
        self.postrec_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.postrec_6.setMinimumSize(QtCore.QSize(51, 21))
        self.postrec_6.setMaximumSize(QtCore.QSize(51, 21))
        self.postrec_6.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.postrec_6.setText("")
        self.postrec_6.setObjectName("postrec_6")
        self.gridLayout.addWidget(self.postrec_6, 18, 4, 1, 1)
        self.bebidas1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas1.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas1.setObjectName("bebidas1")
        self.gridLayout.addWidget(self.bebidas1, 15, 0, 1, 1)
        self.bebidasc4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc4.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc4.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc4.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc4.setObjectName("bebidasc4")
        self.gridLayout.addWidget(self.bebidasc4, 18, 2, 1, 1)
        self.bebidasc3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc3.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc3.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc3.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc3.setObjectName("bebidasc3")
        self.gridLayout.addWidget(self.bebidasc3, 17, 2, 1, 1)
        self.postrec_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.postrec_2.setMinimumSize(QtCore.QSize(51, 21))
        self.postrec_2.setMaximumSize(QtCore.QSize(51, 21))
        self.postrec_2.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.postrec_2.setText("")
        self.postrec_2.setObjectName("postrec_2")
        self.gridLayout.addWidget(self.postrec_2, 13, 4, 1, 1)
        self.fuertec_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_6.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_6.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_6.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_6.setText("")
        self.fuertec_6.setObjectName("fuertec_6")
        self.gridLayout.addWidget(self.fuertec_6, 6, 4, 1, 1)
        self.postrec_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.postrec_3.setMinimumSize(QtCore.QSize(51, 21))
        self.postrec_3.setMaximumSize(QtCore.QSize(51, 21))
        self.postrec_3.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.postrec_3.setText("")
        self.postrec_3.setObjectName("postrec_3")
        self.gridLayout.addWidget(self.postrec_3, 15, 4, 1, 1)
        self.fuerte7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte7.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte7.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte7.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte7.setObjectName("fuerte7")
        self.gridLayout.addWidget(self.fuerte7, 7, 3, 1, 1)
        self.fuerte1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte1.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte1.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte1.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte1.setObjectName("fuerte1")
        self.gridLayout.addWidget(self.fuerte1, 1, 3, 1, 1)
        self.fuerte8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte8.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte8.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte8.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte8.setObjectName("fuerte8")
        self.gridLayout.addWidget(self.fuerte8, 8, 3, 1, 1)
        self.bebidasc6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc6.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc6.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc6.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc6.setObjectName("bebidasc6")
        self.gridLayout.addWidget(self.bebidasc6, 20, 2, 1, 1)
        self.bebidas6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas6.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas6.setObjectName("bebidas6")
        self.gridLayout.addWidget(self.bebidas6, 20, 0, 1, 1)
        self.bebidas5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas5.setMinimumSize(QtCore.QSize(191, 21))
        self.bebidas5.setMaximumSize(QtCore.QSize(191, 21))
        self.bebidas5.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas5.setObjectName("bebidas5")
        self.gridLayout.addWidget(self.bebidas5, 19, 0, 1, 1)
        self.ensaladas_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ensaladas_3.setMinimumSize(QtCore.QSize(191, 21))
        self.ensaladas_3.setMaximumSize(QtCore.QSize(191, 21))
        self.ensaladas_3.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.ensaladas_3.setObjectName("ensaladas_3")
        self.gridLayout.addWidget(self.ensaladas_3, 22, 3, 1, 1)
        self.fuerte6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte6.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte6.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte6.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte6.setObjectName("fuerte6")
        self.gridLayout.addWidget(self.fuerte6, 6, 3, 1, 1)
        self.postre = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.postre.setMinimumSize(QtCore.QSize(191, 21))
        self.postre.setMaximumSize(QtCore.QSize(191, 21))
        self.postre.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.postre.setObjectName("postre")
        self.gridLayout.addWidget(self.postre, 12, 3, 1, 1)
        self.fuerte2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fuerte2.setMinimumSize(QtCore.QSize(191, 21))
        self.fuerte2.setMaximumSize(QtCore.QSize(191, 21))
        self.fuerte2.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.fuerte2.setObjectName("fuerte2")
        self.gridLayout.addWidget(self.fuerte2, 2, 3, 1, 1)
        self.postre_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.postre_3.setMinimumSize(QtCore.QSize(191, 21))
        self.postre_3.setMaximumSize(QtCore.QSize(191, 21))
        self.postre_3.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.postre_3.setObjectName("postre_3")
        self.gridLayout.addWidget(self.postre_3, 15, 3, 1, 1)
        self.ensaladas = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ensaladas.setMinimumSize(QtCore.QSize(191, 21))
        self.ensaladas.setMaximumSize(QtCore.QSize(191, 21))
        self.ensaladas.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.ensaladas.setObjectName("ensaladas")
        self.gridLayout.addWidget(self.ensaladas, 20, 3, 1, 1)
        self.fuertec = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec.setText("")
        self.fuertec.setObjectName("fuertec")
        self.gridLayout.addWidget(self.fuertec, 1, 4, 1, 1)
        self.postrec = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.postrec.setMinimumSize(QtCore.QSize(51, 21))
        self.postrec.setMaximumSize(QtCore.QSize(51, 21))
        self.postrec.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.postrec.setText("")
        self.postrec.setObjectName("postrec")
        self.gridLayout.addWidget(self.postrec, 12, 4, 1, 1)
        self.bebidasc10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc10.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc10.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc10.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc10.setObjectName("bebidasc10")
        self.gridLayout.addWidget(self.bebidasc10, 24, 2, 1, 1)
        self.bebidas4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas4.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas4.setObjectName("bebidas4")
        self.gridLayout.addWidget(self.bebidas4, 18, 0, 1, 1)
        self.fuertec_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_7.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_7.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_7.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_7.setText("")
        self.fuertec_7.setObjectName("fuertec_7")
        self.gridLayout.addWidget(self.fuertec_7, 7, 4, 1, 1)
        self.bebidas9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas9.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas9.setObjectName("bebidas9")
        self.gridLayout.addWidget(self.bebidas9, 23, 0, 1, 1)
        self.ensaladac_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ensaladac_2.setMinimumSize(QtCore.QSize(51, 21))
        self.ensaladac_2.setMaximumSize(QtCore.QSize(51, 21))
        self.ensaladac_2.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.ensaladac_2.setText("")
        self.ensaladac_2.setObjectName("ensaladac_2")
        self.gridLayout.addWidget(self.ensaladac_2, 21, 4, 1, 1)
        self.bebidasc2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.bebidasc2.setMinimumSize(QtCore.QSize(51, 21))
        self.bebidasc2.setMaximumSize(QtCore.QSize(51, 21))
        self.bebidasc2.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.bebidasc2.setObjectName("bebidasc2")
        self.gridLayout.addWidget(self.bebidasc2, 16, 2, 1, 1)
        self.fuertec_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_4.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_4.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_4.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_4.setText("")
        self.fuertec_4.setObjectName("fuertec_4")
        self.gridLayout.addWidget(self.fuertec_4, 4, 4, 1, 1)
        self.bebidas3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.bebidas3.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.bebidas3.setObjectName("bebidas3")
        self.gridLayout.addWidget(self.bebidas3, 17, 0, 1, 1)
        self.fuertec_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fuertec_2.setMinimumSize(QtCore.QSize(51, 21))
        self.fuertec_2.setMaximumSize(QtCore.QSize(51, 21))
        self.fuertec_2.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.fuertec_2.setText("")
        self.fuertec_2.setObjectName("fuertec_2")
        self.gridLayout.addWidget(self.fuertec_2, 2, 4, 1, 1)
        self.ensaladac = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ensaladac.setMinimumSize(QtCore.QSize(51, 21))
        self.ensaladac.setMaximumSize(QtCore.QSize(51, 21))
        self.ensaladac.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.ensaladac.setText("")
        self.ensaladac.setObjectName("ensaladac")
        self.gridLayout.addWidget(self.ensaladac, 20, 4, 1, 1)
        self.entradac9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac9.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac9.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac9.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac9.setObjectName("entradac9")
        self.gridLayout.addWidget(self.entradac9, 9, 2, 1, 1)
        self.entradac1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac1.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac1.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac1.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac1.setText("")
        self.entradac1.setObjectName("entradac1")
        self.gridLayout.addWidget(self.entradac1, 1, 2, 1, 1)
        self.entrada8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada8.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada8.setObjectName("entrada8")
        self.gridLayout.addWidget(self.entrada8, 8, 0, 1, 1)
        self.entradac2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac2.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac2.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac2.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac2.setObjectName("entradac2")
        self.gridLayout.addWidget(self.entradac2, 2, 2, 1, 1)
        self.entradac6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac6.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac6.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac6.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac6.setObjectName("entradac6")
        self.gridLayout.addWidget(self.entradac6, 6, 2, 1, 1)
        self.entrada6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada6.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada6.setObjectName("entrada6")
        self.gridLayout.addWidget(self.entrada6, 6, 0, 1, 1)
        self.entrada1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada1.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada1.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada1.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada1.setObjectName("entrada1")
        self.gridLayout.addWidget(self.entrada1, 1, 0, 1, 1)
        self.entrada2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada2.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada2.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada2.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada2.setObjectName("entrada2")
        self.gridLayout.addWidget(self.entrada2, 2, 0, 1, 1)
        self.entrada3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada3.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada3.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada3.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada3.setObjectName("entrada3")
        self.gridLayout.addWidget(self.entrada3, 3, 0, 1, 1)
        self.entradac10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac10.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac10.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac10.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac10.setObjectName("entradac10")
        self.gridLayout.addWidget(self.entradac10, 10, 2, 1, 1)
        self.entradac4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac4.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac4.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac4.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac4.setObjectName("entradac4")
        self.gridLayout.addWidget(self.entradac4, 4, 2, 1, 1)
        self.entrada5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada5.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada5.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada5.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada5.setObjectName("entrada5")
        self.gridLayout.addWidget(self.entrada5, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.entrada7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada7.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada7.setObjectName("entrada7")
        self.gridLayout.addWidget(self.entrada7, 7, 0, 1, 1)
        self.entradac8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac8.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac8.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac8.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac8.setObjectName("entradac8")
        self.gridLayout.addWidget(self.entradac8, 8, 2, 1, 1)
        self.entradac7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac7.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac7.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac7.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac7.setObjectName("entradac7")
        self.gridLayout.addWidget(self.entradac7, 7, 2, 1, 1)
        self.entrada9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada9.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada9.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada9.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada9.setObjectName("entrada9")
        self.gridLayout.addWidget(self.entrada9, 9, 0, 1, 1)
        self.entradac3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.entradac3.setMinimumSize(QtCore.QSize(51, 21))
        self.entradac3.setMaximumSize(QtCore.QSize(51, 21))
        self.entradac3.setStyleSheet("border: 1px solid #333333;\n"
"border-radius: 10px;\n"
"border: 2px solid #5d432c;")
        self.entradac3.setObjectName("entradac3")
        self.gridLayout.addWidget(self.entradac3, 3, 2, 1, 1)
        self.entrada4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada4.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada4.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada4.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada4.setObjectName("entrada4")
        self.gridLayout.addWidget(self.entrada4, 4, 0, 1, 1)
        self.entrada10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.entrada10.setMinimumSize(QtCore.QSize(191, 21))
        self.entrada10.setMaximumSize(QtCore.QSize(191, 21))
        self.entrada10.setStyleSheet("background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333")
        self.entrada10.setObjectName("entrada10")
        self.gridLayout.addWidget(self.entrada10, 10, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.encargado_name = QtWidgets.QLabel(self.widget)
        self.encargado_name.setGeometry(QtCore.QRect(170, 10, 291, 31))
        self.encargado_name.setMinimumSize(QtCore.QSize(291, 31))
        self.encargado_name.setMaximumSize(QtCore.QSize(291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.encargado_name.setFont(font)
        self.encargado_name.setStyleSheet("background-color: #f5f5f5;\n"
"border-left: 2px solid #5d432c;\n"
"border-top: 2px solid #5d432c;\n"
"border-bottom: 2px solid #5d432c;\n"
"border-right: 2px solid #5d432c;\n"
"\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"\n"
"color: #333333")
        self.encargado_name.setAlignment(QtCore.Qt.AlignCenter)
        self.encargado_name.setObjectName("encargado_name")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 101, 31))
        self.label_2.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #f5f5f5;\n"
"border-left: 2px solid #5d432c;\n"
"border-top: 2px solid #5d432c;\n"
"border-bottom: 2px solid #5d432c;\n"
"border-right: 0;\n"
"\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"color: #333333;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Ordenar = QtWidgets.QPushButton(self.widget)
        self.Ordenar.setGeometry(QtCore.QRect(830, 210, 101, 51))
        self.Ordenar.setMinimumSize(QtCore.QSize(101, 51))
        self.Ordenar.setStyleSheet("QPushButton {\n"
"       background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"         stop:0 #b8ff92, stop:1 #aaff65);\n"
"       color: Black;\n"
"       border-radius: 10px;\n"
"       border: none;\n"
"        font: 63 italic 8pt \"Sitka Small Semibold\" ;\n"
"      }\n"
"      QPushButton:hover {\n"
"       background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"         stop:0 #aaff65, stop:1  #b8ff92);\n"
"      }\n"
"      QPushButton:pressed {\n"
"      }")
        self.Ordenar.setObjectName("Ordenar")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 140, 101, 51))
        self.pushButton_2.setMinimumSize(QtCore.QSize(101, 51))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"       background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"         stop:0 #b8ff92, stop:1 #aaff65);\n"
"       color: Black;\n"
"       border-radius: 10px;\n"
"       border: none;\n"
"        font: 63 italic 8pt \"Sitka Small Semibold\" ;\n"
"      }\n"
"      QPushButton:hover {\n"
"       background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"         stop:0 #aaff65, stop:1  #b8ff92);\n"
"      }\n"
"      QPushButton:pressed {\n"
"      }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(830, 100, 101, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background: #2a2a2a;\n"
"    border: 1px solid #c7a17a;\n"
"    border-radius: 10px;\n"
"    color: #c7a17a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #2a2a2a;;\n"
"    color: #c7a17a;\n"
"}\n"
"QComboBox::item:selected {\n"
"    background: #2a2a2a;\n"
"    color: #c7a17a; \n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 771, 461))
        self.label_4.setStyleSheet("background-color: #f5f5f5;\n"
"border-radius: 50px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.scrollArea.raise_()
        self.encargado_name.raise_()
        self.label_2.raise_()
        self.Ordenar.raise_()
        self.pushButton_2.raise_()
        self.comboBox.raise_()
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 111, 501))
        self.widget_2.setStyleSheet("background-color: #f5f5f5;\n"
"border-right: 2px solid #5d432c;")
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 450, 93, 41))
        self.pushButton.setStyleSheet("background-color: #bd2c00;\n"
"border: 1px solid #f5f5f5;\n"
"border-radius: 10px;\n"
"padding: 10px 20px;\n"
"font: 63 italic 8pt \"Sitka Small Semibold\" ;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 31))
        self.label.setMinimumSize(QtCore.QSize(71, 31))
        self.label.setMaximumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small Semibold")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background-color: #f5f5f5;\n"
"border: 2px solid #5d432c;\n"
"border-radius: 10px;\n"
"color: #333333\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.postre_6.setText(_translate("Form", "Buñuelos con miel"))
        self.postre_5.setText(_translate("Form", "Nieve Artesanal"))
        self.ensaladas_2.setText(_translate("Form", "Arroz rojo o blanco"))
        self.postre_4.setText(_translate("Form", "Churros con Cajeta"))
        self.label_18.setText(_translate("Form", "𝓔𝓷𝓼𝓪𝓵𝓪𝓭𝓪𝓼"))
        self.ensaladas_4.setText(_translate("Form", "Papas Gajo"))
        self.postre_2.setText(_translate("Form", "Dulce de Calabaza"))
        self.ensaladas_5.setText(_translate("Form", "Arroz negro y tinta de calamar"))
        self.bebidas8.setText(_translate("Form", "Michelada"))
        self.fuerte3.setText(_translate("Form", "Tacos al pastor"))
        self.label_17.setText(_translate("Form", "𝓕𝓾𝓮𝓻𝓽𝓮"))
        self.fuerte5.setText(_translate("Form", "Mole Poblano"))
        self.label_16.setText(_translate("Form", "𝓹𝓸𝓼𝓽𝓻𝓮𝓼"))
        self.bebidas10.setText(_translate("Form", "Charro Negro"))
        self.label_12.setText(_translate("Form", "𝓑𝓮𝓫𝓲𝓭𝓪𝓼"))
        self.fuerte4.setText(_translate("Form", "Chiles en Nogada"))
        self.bebidas7.setText(_translate("Form", "Paloma"))
        self.bebidas2.setText(_translate("Form", "Agua de Jamaica"))
        self.bebidas1.setText(_translate("Form", "Agua de Horchata"))
        self.fuerte7.setText(_translate("Form", "Chocinita Pibil"))
        self.fuerte1.setText(_translate("Form", "Enchiladas verdes o rojas"))
        self.fuerte8.setText(_translate("Form", "Tacos de Arrachera"))
        self.bebidas6.setText(_translate("Form", "Margarita"))
        self.bebidas5.setText(_translate("Form", "Limonada"))
        self.ensaladas_3.setText(_translate("Form", "Platanos fritos"))
        self.fuerte6.setText(_translate("Form", "Tampiqueña de Res"))
        self.postre.setText(_translate("Form", "Flan"))
        self.fuerte2.setText(_translate("Form", "Pozole rojo"))
        self.postre_3.setText(_translate("Form", "Pan de Elote"))
        self.ensaladas.setText(_translate("Form", "Ensalada de Nopales"))
        self.bebidas4.setText(_translate("Form", "Refresco Embotellado"))
        self.bebidas9.setText(_translate("Form", "Caballito de Mezcal"))
        self.bebidas3.setText(_translate("Form", "Agua de Tamarindo"))
        self.entrada8.setText(_translate("Form", "Quesadillas de huitlacoche"))
        self.entrada6.setText(_translate("Form", "Chalupas poblanas"))
        self.entrada1.setText(_translate("Form", "Guacamole con Totopos"))
        self.entrada2.setText(_translate("Form", "Queso Fundido"))
        self.entrada3.setText(_translate("Form", "Esquites"))
        self.entrada5.setText(_translate("Form", "Tacos dorados con papa"))
        self.label_3.setText(_translate("Form", "𝓔𝓷𝓽𝓻𝓪𝓭𝓪𝓼"))
        self.entrada7.setText(_translate("Form", "Chicharron en salsa verde"))
        self.entrada9.setText(_translate("Form", "Quesadillas de flor de calabaza"))
        self.entrada4.setText(_translate("Form", "Sopes Surtidos"))
        self.entrada10.setText(_translate("Form", "Tlacoyos de nopales"))
        self.encargado_name.setText(_translate("Form", "nombre empleado"))
        self.label_2.setText(_translate("Form", "Encargado:"))
        self.Ordenar.setText(_translate("Form", "Ordenar"))
        self.pushButton_2.setText(_translate("Form", "Editar"))
        self.comboBox.setItemText(0, _translate("Form", "MESA 1"))
        self.comboBox.setItemText(1, _translate("Form", "MESA 2"))
        self.comboBox.setItemText(2, _translate("Form", "MESA 3"))
        self.comboBox.setItemText(3, _translate("Form", "MESA 4"))
        self.comboBox.setItemText(4, _translate("Form", "MESA 5"))
        self.comboBox.setItemText(5, _translate("Form", "MESA 6"))
        self.comboBox.setItemText(6, _translate("Form", "MESA 7"))
        self.comboBox.setItemText(7, _translate("Form", "MESA 8"))
        self.comboBox.setItemText(8, _translate("Form", "MESA 9"))
        self.comboBox.setItemText(9, _translate("Form", "MESA 10"))
        self.comboBox.setItemText(10, _translate("Form", "MESA 11"))
        self.comboBox.setItemText(11, _translate("Form", "MESA 12"))
        self.comboBox.setItemText(12, _translate("Form", "MESA 13"))
        self.comboBox.setItemText(13, _translate("Form", "MESA 14"))
        self.comboBox.setItemText(14, _translate("Form", "MESA 15"))
        self.comboBox.setItemText(15, _translate("Form", "MESA 16"))
        self.comboBox.setItemText(16, _translate("Form", "MESA 17"))
        self.comboBox.setItemText(17, _translate("Form", "MESA 18"))
        self.comboBox.setItemText(18, _translate("Form", "MESA 19"))
        self.comboBox.setItemText(19, _translate("Form", "MESA 20"))
        self.pushButton.setText(_translate("Form", "Salir"))
        self.label.setText(_translate("Form", "Menu"))
